import type { AutoTraderConfig, RiskSettings } from "@/src/domain/models";
export const defaultRiskSettings: RiskSettings = {
  autoTraderEnabled: true,
  autoTraderAllocatedCapital: 25000,
  maximumCapitalPerTrade: 2500,
  maximumRiskPerTrade: 250,
  dailyMaximumLoss: 750,
  dailyProfitTarget: 1000,
  maximumTradesPerDay: 8,
  maximumConcurrentPositions: 4,
  maximumPortfolioExposure: 70,
  maximumPortfolioDrawdown: 12,
  maximumExposurePerAsset: 20,
  bigMoneyApprovalThreshold: 85,
};
export const defaultAutoTraderConfig: AutoTraderConfig = {
  enabled: false,
  capitalAllocation: 25000,
  maximumTradeSize: 2500,
  maximumRiskPerTrade: 250,
  dailyLossLimit: 750,
  dailyProfitTarget: 1000,
  maximumTradesPerDay: 8,
  maximumConcurrentPositions: 4,
  minimumStrategyScore: 70,
  allowedStrategies: [
    "Trend Following",
    "Momentum",
    "Breakout",
    "Mean Reversion",
  ],
  allowedAssets: ["AAPL", "NVDA", "MSFT", "AMZN"],
  riskProfile: "BALANCED",
  maximumPortfolioExposure: 50,
  minimumOpportunityScore: 75,
  minimumConfidence: 65,
  minimumHistoricalScore: 0,
  longEnabled: true,
  shortEnabled: false,
  sessionStart: "09:30",
  sessionEnd: "16:00",
  sessionTimezone: "America/New_York",
  entryStart: "09:35",
  lastEntryTime: "15:15",
  forceExitTime: "15:50",
  maximumHoldMinutes: 120,
  minimumExitScore: 45,
  strategyHealthMinimumSample: 20,
  cooldownMinutes: 60,
  lossCooldownMinutes: 240,
  paperTestMode: false,
  paperTestTargetAutoPositions: 8,
  paperBigMoneyTestMode: false,
  paperTestTargetBigMoneyPositions: 2,
  paperBigMoneyAutoApproveTest: false,
  paperTestMinimumOpportunityScore: 60,
  paperTestMinimumConfidence: 50,
  paperTestMaximumPositionSize: 1000,
  paperTestMaximumRiskPerTrade: 100,
  paperTestMaximumDailyTrades: 30,
  paperTestUniverse: [
    "AAPL",
    "MSFT",
    "NVDA",
    "AMD",
    "AMZN",
    "META",
    "GOOGL",
    "TSLA",
    "SPY",
    "QQQ",
    "NFLX",
    "IWM",
  ],
};
