alter table auto_trader_config add column if not exists risk_profile text not null default 'BALANCED';
alter table auto_trader_config add column if not exists maximum_portfolio_exposure numeric not null default 50;
alter table auto_trader_config add column if not exists minimum_opportunity_score integer not null default 75;
alter table auto_trader_config add column if not exists minimum_confidence integer not null default 65;
alter table auto_trader_config add column if not exists minimum_historical_score integer not null default 0;
alter table auto_trader_config add column if not exists long_enabled boolean not null default true;
alter table auto_trader_config add column if not exists short_enabled boolean not null default false;
alter table auto_trader_config add column if not exists session_start time not null default '09:30';
alter table auto_trader_config add column if not exists session_end time not null default '16:00';
alter table auto_trader_config add column if not exists session_timezone text not null default 'America/New_York';
alter table auto_trader_config add column if not exists cooldown_minutes integer not null default 60;
alter table auto_trader_config add column if not exists loss_cooldown_minutes integer not null default 240;
create table if not exists autonomous_candidate_evaluations (id uuid primary key default gen_random_uuid(), user_id uuid not null references profiles(id) on delete cascade, cycle_key text not null, symbol text not null, strategy text not null, signal text not null, scores jsonb not null, market_regime text not null, portfolio_context jsonb not null, sizing jsonb, decision text not null, reasons jsonb not null default '[]', selected boolean not null default false, created_at timestamptz not null default now(), unique(user_id,cycle_key,symbol,strategy));
create table if not exists autonomous_execution_claims (id uuid primary key default gen_random_uuid(), user_id uuid not null references profiles(id) on delete cascade, execution_key text not null, candidate_id uuid references autonomous_candidate_evaluations(id), state text not null check(state in ('CLAIMED','SUBMITTED','CONFIRMED','REJECTED','UNKNOWN')), broker_order_id text, broker_result jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(user_id,execution_key));
create table if not exists broker_reconciliation_runs (id uuid primary key default gen_random_uuid(), user_id uuid not null references profiles(id) on delete cascade, account jsonb not null, positions jsonb not null, orders jsonb not null, fills jsonb not null, differences jsonb not null default '[]', status text not null, created_at timestamptz not null default now());
create table if not exists dashboard_preferences (user_id uuid primary key references profiles(id) on delete cascade, layout jsonb not null default '["status","account","chart","positions","risk","markets","opportunities","health"]', display_currency text not null default 'USD' check(display_currency in ('USD','ZAR','GBP','EUR')), watchlist jsonb not null default '["SPY","QQQ","DIA","IWM","AAPL","MSFT","NVDA","AMZN","META","GOOGL","AMD","TSLA"]', updated_at timestamptz not null default now());
alter table paper_positions add column if not exists exit_reason text;
alter table autonomous_candidate_evaluations enable row level security; alter table autonomous_execution_claims enable row level security; alter table broker_reconciliation_runs enable row level security; alter table dashboard_preferences enable row level security;
create policy "Owners read autonomous evaluations" on autonomous_candidate_evaluations for select using(auth.uid()=user_id);
create policy "Owners read autonomous claims" on autonomous_execution_claims for select using(auth.uid()=user_id);
create policy "Owners read reconciliation" on broker_reconciliation_runs for select using(auth.uid()=user_id);
create policy "Owners manage dashboard preferences" on dashboard_preferences for all using(auth.uid()=user_id) with check(auth.uid()=user_id);
